//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestM.Data
{
    using System;

    public partial class Employee
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
    }
}
